name: econ
ckpt_dir: "/var/locally-mounted/myshareddir/Fulden/ckpt/"
normal_path: "/var/locally-mounted/myshareddir/Fulden/ckpt/normal.ckpt"
ifnet_path: "/var/locally-mounted/myshareddir/Fulden/ckpt/ifnet.ckpt"
results_path: "./results"

net:
  in_nml: (('image', 3), ('image_back', 3), ('T_normal_F', 3), ('T_normal_B', 3))
  in_geo: (('normal_F',3), ('normal_B',3))

test_mode: True
batch_size: 1

dataset:
  prior_type: "SMPL"

vol_res: 256
mcube_res: 256
clean_mesh: True
cloth_overlap_thres: 0.50
body_overlap_thres: 0.00
force_smpl_optim: True


# normal_model could be '1b' if CUDA OOM, see apps/sapiens.py

sapiens:
  use: True
  seg_model: "fg-bg-1b"
  normal_model: "0.3b" 

# For crowded / occluded scene
# body_overlap_thres: 0.98

bni:
  k: 4
  lambda1: 1e-4
  boundary_consist: 1e-6
  poisson_depth: 10
  use_smpl: ["face"]
  # use_smpl: ["face"]
  # use_ifnet: True
  use_ifnet: False
  use_poisson: False
  # hand_thres: 8e-2
  # face_thres: 6e-2
  hand_thres: 0.05
  face_thres: 0.01
  thickness: 0.01
  hps_type: "pixie"
  texture_src: "image"
  cut_intersection: True